[technote]
id = "RTN-068"
series_id = "RTN"
canonical_url = "https://rtn-068.lsst.io/"
github_url = "https://github.com/lsst/rtn-068"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
[[technote.authors]]
name = {given = "William", family = "O'Mullane"}
internal_id = "omullanew"
orcid = "https://orcid.org/0000-0003-4141-6195"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
